### PR TITLE
Fix major normal problems on the forearm. 

### PR DESCRIPTION
**Pull request by adamrr**
This fixes major normal issues with the forearm and minor geometry problems across other parts.
I am providing images here for before/after since I don't expect anyone to dig into the collada files.

before
Before

after
After

What are normals? If you're not familiar with them in the geometric sense, a normal is a vector.
Let's say we have a plane, its normal is defined by some vector in space. It is exaggerated by the green arrow.
plane
This normal helps us with lighting calculations as it defines which way the plane is facing. The picture depicts a "face normal", but each vertex also has a normal. That's an oversimplification, but for context -- that's what this PR is fixing.

A closer look reveals extra geometry in the original, but the highlight is the fact that the normals are at arbitrary angles to the surface. See the red arrows.
bad_normals
Bad normals

Upon removing extra geometry, the normals along the edges are now perpendicular to the surface, which helps sell the illusion that it's a solid. See the green arrows.
good_normals
Better normals

### CODE REVIEW

**Review by mechterp10 — APPROVED** [review]

**Comment by mechterp10** [comment]
Is it bad that I cannot visually tell a difference on the models?

**Comment by adamrr** [comment]
No, It's subtle. I might be able to highlight it and re-upload an image. It's on the forearm primarily.

**Review by michelle-avery — APPROVED** [review]
:+1: for the extra effort on the description

**Review by adamcalhoon — APPROVED** [review]
Beautiful! I can see the difference.

**Review by joeporembski — APPROVED** [review]
I'll trust your judgement here. I know what you're talking about, but I don't don't have the eye for it when it comes to looking at the image holistically.

**Pull request merged**
